// HD's main ZScript lump.

version "4.11"
#include "ZScript/MACZombie.zsc"
#include "ZScript/ColtZombie.zsc"
#include "ZScript/ACRZombie_Old.zsc"
#include "ZScript/Bulldozer.zsc"

//#include "ZScript/Weapons/M4Flechette.zsc"

class PB_HDCaesarSaladSpawner : EventHandler
{
override void CheckReplacement(ReplaceEvent e) {
	if (!PB_CaesarSalad_AllowReplacement)
		return;
	switch (e.Replacee.GetClassName()) {
	
	//Andy McNab look-a-like
		case 'ZombieMan' 	: if (!random(0, 3)) 
		{
			if(random(0,1)){e.Replacement = "PB_UndeadHomeslice";}
			else{e.Replacement = "PB_ColtSMGZombie";}
		}	
		break;
		
		case 'ShotgunGuy' 	: if (!random(0, 3)) 
		{
			if(random(0,1)){e.Replacement = "PB_UndeadHomeslice";}
			else{e.Replacement = "PB_ColtSMGZombie";}
		}	
		break;
		
		case 'ChaingunGuy' 	: if (!random(0, 2))		
		{
			if(random(0,1)){e.Replacement = "PB_ACRZombie";}
			else{e.Replacement = "PB_ACRZombie";} 
			
			//placeholder since I'm planning to have a different enemy also spawn on the chaingunner
		}
		
		case 'HellKnight' 	: if (!random(0, 2))		
		{
			if(random(0,1)){e.Replacement = "PB_DozerZombie";}
			else{e.Replacement = "PB_DozerZombie";} 
		}	
		
		break;
		
		}
	e.IsFinal = false;
	}
		
		
	//honestly considering whether i should really keep the AR-15 or not
	
	/*
	void PushItem(Actor T, string item) {
		let A = HDPickup(T);
		A.itemsthatusethis.push(item);
	}

	override void WorldThingSpawned(WorldEvent e) {
		let T = e.Thing;
		
		// Null check for event removal. 
		if(!T)return;
		
		switch (T.GetClassName()) {
		
		case 'HD6mmFlechetteAmmo':
			PushItem(T, "HDColtCommando_CS");
			break;
			
		case 'PB_HDSteyrACRMag':
			PushItem(T, "HDColtCommando_CS");
			break;
		}
	}
	*/
}